### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by xseignard** [moovel/node-yolo#23]
Hello,
When trying to run the examples I get a Segmentation Fault.
Here is my conf: Hackintosh, macOS Sierra 10.12.6, clang 9.0.0

I tried to do a npm rebuild of the node_modules, with no more luck.

I also have some warnings ( when doing this `npm rebuild`:
```
yolo9000-test % npm rebuild     

> @moovel/yolo@0.2.0 install /Users/bigx/repos/yolo9000-test/node_modules/@moovel/yolo
> node-gyp rebuild

  CXX(target) Release/obj.target/darknet/darknet.o
  CXX(target) Release/obj.target/darknet/src/demo.o
  SOLINK_MODULE(target) Release/darknet.node
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
ld: warning: object file (/usr/local/lib/libdarknet.a(image.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(box.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(utils.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(detection_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(data.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(region_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(parser.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(network.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(option_list.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(activations.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(blas.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(convolutional_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(matrix.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(list.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(cost_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(tree.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(cuda.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(activation_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(avgpool_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(batchnorm_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(connected_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(crnn_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(crop_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(deconvolutional_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(dropout_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(gru_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(local_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(lstm_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(maxpool_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(normalization_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(reorg_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(rnn_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(route_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(shortcut_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(softmax_layer.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(col2im.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(gemm.o)) was built for newer OSX version (10.12) than being linked (10.7)
ld: warning: object file (/usr/local/lib/libdarknet.a(im2col.o)) was built for newer OSX version (10.12) than being linked (10.7)
@moovel/yolo@0.2.0 /Users/bigx/repos/yolo9000-test/node_modules/@moovel/yolo
bindings@1.2.1 /Users/bigx/repos/yolo9000-test/node_modules/bindings
nan@2.7.0 /Users/bigx/repos/yolo9000-test/node_modules/nan
```

I don't know is the segfault and this are related, but I cannot run it.
Any idea?

Regards

**Comment by OrKoN** [comment]
@xseignard Hi, what's the opencv version you compile with?

**Comment by xseignard** [comment]
Hello @OrKoN thanks for your quick response.
I installed opencv with `brew install opencv` so version 3.3.0_3 right now.

Regards

**Comment by OrKoN** [comment]
@xseignard this project is using the version 2. In particular, I compile with 2.4.9.1

**Comment by xseignard** [comment]
Thanks, I tried with the opencv version 2.4.13.2 from `brew install opencv@2`

I succeeded to build and install the darknet fork with:
```
PKG_CONFIG_PATH=/usr/local/opt/opencv@2/lib/pkgconfig make OPENCV=1
```

Now when I try to install the npm package (via `npm i @moovel/yolo`) I have the following error:
```
../src/demo.cc:18:10: fatal error: 'opencv2/highgui/highgui_c.h' file not found
#include "opencv2/highgui/highgui_c.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

This is the same error I had trying to compile darknet, fixed with the `PKG_CONFIG_PATH=/usr/local/opt/opencv@2/lib/pkgconfig`. So I tried the same with npm with no success.

Any idea?

Regards,

Xavier

**Comment by OrKoN** [comment]
@xseignard the project compiles with this lib flags https://github.com/moovel/node-yolo/blob/master/binding.gyp#L36 It expects that this can be resolved on the system. I am not sure if it can be solved via PKG_CONFIG_PATH somehow.

**Comment by OrKoN** [comment]
Also we use the following script to test if OPENCV is available https://github.com/moovel/node-yolo/blob/master/util/has_lib.js

**Comment by xseignard** [comment]
Hello again,

I did some changes (ugly ones) to the util and the gyp:
https://github.com/xseignard/node-yolo/blob/master/util/has_lib.js#L28
https://github.com/xseignard/node-yolo/blob/master/binding.gyp#L22
https://github.com/xseignard/node-yolo/blob/master/binding.gyp#L36

I can now build the project, but I still have a problem when running the examples:
```
dyld: lazy symbol binding failed: Symbol not found: _cvLoadImage
  Referenced from: /Users/bigx/repos/node-yolo/build/Release/darknet.node
  Expected in: flat namespace

dyld: Symbol not found: _cvLoadImage
  Referenced from: /Users/bigx/repos/node-yolo/build/Release/darknet.node
  Expected in: flat namespace

[1]    46989 abort      node darknetTest.js
```

To be honest, I only have a slight idea of what I'm doing :)

**Comment by OrKoN** [comment]
@xseignard it looks like it could not link opencv. _cvLoadImage is the function from opencv. Perhaps it found the header files but didn't find the lib files.

**Comment by xseignard** [comment]
Yeah, in the meantime I gave up brew to try to build opencv, now I have problems with the output of pkg-config

```
darknet [b61bcf5...] % pkg-config --libs opencv
-L/usr/local/lib -L/usr/local/share/OpenCV/3rdparty/lib -lopencv_contrib -lopencv_stitching -lopencv_nonfree -lopencv_superres -lopencv_ts -lopencv_videostab -lopencv_gpu -lopencv_photo -lopencv_objdetect -lopencv_legacy -lopencv_video -lopencv_ml -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lIlmImf -ljasper -ltiff -lpng -ljpeg -lopencv_imgproc -lopencv_flann -lopencv_core -lzlib -l-framework QuartzCore -l-framework CoreVideo -l-framework CoreMedia -l-framework CoreGraphics -l-framework AVFoundation -l-framework Accelerate -l-framework Cocoa -lstdc++
```

All the `-l-framework` args make the `make` command on darknet fail with the following:
```
clang: fatal error: no such file or directory:  'XXX'
```

Very hard to get the whole stuff working on macos, are you using macos?

**Comment by OrKoN** [comment]
I use MacOS (Sierra) and I didn't have any problems. I have installed opencv a while ago and I didn't change it. But my teammates were able to get it running following the instructions quite recently. Sorry, I have no idea why opencv is not installing properly. Are you sure you were able to build the darknet itself? did you try to run original demo from darknet?

**Comment by xseignard** [comment]
Yeah, I can run the original yolo-9000 without issues (although very slow) see:
![capture d ecran 2017-10-10 a 17 38 26](https://user-images.githubusercontent.com/515603/31395860-1767a83c-ade2-11e7-9ff3-97c6a8e69187.png)

What is the process you followed to build and install opencv?

**Comment by OrKoN** [comment]
it says "car" :-D I cannot remember exactly how I installed. But @b-g and @joeyklee installed it recently: could you perhaps help?

What I also noticed is that our readme says that "Apple LLVM version 8.0.0 (xcode 8.2, check version with clang -v)" is required. Can it be the case? you seem to have a newer version?

I will check tomorrow on my mac how I exactly have it installed. Perhaps it's worth documenting because all those native dependencies don't seem to be quite stable :-(

**Comment by xseignard** [comment]
Thanks!

**Comment by OrKoN** [comment]
@xseignard actually I have it installed via brew too: opencv 2.4.13.1. And my clang and Sierra version are the same. I have dylib files for opencv at /usr/local/lib/libopencv_* and all the headers at /usr/local/include/opencv2/.

**Comment by xseignard** [comment]
Thanks, so you symlinked that manually since opencv@2 is a keg-only formulae?

I'll try this again today. 

Best regards

**Comment by OrKoN** [comment]
@xseignard I don't think I have symlinked manually - I assume it has been installed like this automatically

**Comment by xseignard** [comment]
Well, very weird, since `opencv@2` is an alternate version of the `opencv` brew formula (e.g. keg only).

In the case of a keg only formula, brew don't symlink the formula, so it wouldn't be possible to have theses symlinks in `/usr/local` without other user actions.

I had to do the following in order to have opencv (version 2.4.13.2) installed and with the right symlinks:
```
brew install opencv@2
sudo chown -R $(whoami):admin /usr/local
brew link --force opencv@2
```

Now everything is working as expected.

Thanks for your work and for your patience on my issue.

Best regards!

**Comment by OrKoN** [comment]
@xseignard thanks for the info! I will update the doc with this
